Homework 30 Kubernetes 3
Otus-DevOps-2017-11/f4rx_microservices pull request #13
Opened 2018-03-31 19:34 UTC by f4rx

Выполнено основное задание.

В задание мы "игрались" с сетями и различными персистент томами. Выполнено по методичке, в readme ничего не добавлял.

2018-05-02 12:58 UTC, vitkhab requested changes
В ДЗ есть задание описать секрет с TLS-сертификатом в виде yaml-конфигурации kubernetes. 

Для зачета ДЗ необходимо:
- исправить mongo-claim-dynamic.yml
- исправить post-mongodb-service.yml

2018-05-02 12:58 UTC, vitkhab commented on kubernetes/mongo-claim-dynamic.yml
> +  storageClassName: slow
С этой конфигурацией не поднимается инстанс mongodb. Есть понимание почему?

В гисте, откуда была скачана конфигурация, была допущена ошибка.

2018-05-02 12:58 UTC, vitkhab commented on kubernetes/post-mongodb-service.yml
> +
Куда-то пропала строка `post-db: "true"`

2018-05-02 13:44 UTC, f4rx commented
>Для зачета ДЗ необходимо:

Ну да, я конечно сейчас вспомню, что я делал месяц назад..

> В гисте, откуда была скачана конфигурация, была допущена ошибка.

Огонь!

2018-05-06 11:46 UTC, f4rx commented
>Для зачета ДЗ необходимо:
>исправить mongo-claim-dynamic.yml
>исправить post-mongodb-service.yml

исправлено

2018-05-17 08:46 UTC, vitkhab approved these changes
Спасибо за внесенные изменения!

2018-05-17 13:38 UTC, merged